spring.application.name=universityERP

spring.datasource.url=jdbc:sqlserver://universityerpserversithari.database.windows.net:1433;database=universityerpdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

spring.datasource.username=erpadmin
spring.datasource.password=UniERP@2026!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

app.auth.username=admin
app.auth.password=admin123