spring.application.name=universityERP

# Local MySQL
spring.datasource.url=jdbc:mysql://127.0.0.1:3307/university_erp?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server
server.port=8080

# Auth
app.auth.username=admin
app.auth.password=admin123
`