# Replace with your actual database details
spring.datasource.url=jdbc:sqlserver://erpdatabase.database.windows.net:1433;databaseName=YOUR_DB_NAME;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=CloudSAd1d3d517@erpdatabase
spring.datasource.password=n9v5ZH@12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Remove this line if it exists:
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect