# Azure MySQL Database Configuration
spring.datasource.url=jdbc:mysql://university-erp-db.mysql.database.azure.com:3306/university_db?useSSL=true&requireSSL=false
spring.datasource.username=dbadmin
spring.datasource.password=SHchi2002@ERp

# Database Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Settings (Tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect